SET DEFINE OFF;
SET SERVEROUTPUT ON;

DECLARE
SCHEMA_NAME VARCHAR2(15):='Schema_Name'; 
CREATE_DDL VARCHAR2(32000); 
type tab_name_array_type is table of varchar2(1000);
tab_name_array tab_name_array_type := tab_name_array_type('Table1', 'Table2');

BEGIN
	DBMS_OUTPUT.ENABLE(1000000);
	DBMS_OUTPUT.PUT_LINE ('-- **START : LOOPING THORUGH Oracle TABLES & Generating Redshift DDLs **');
  
	FOR i IN 1..tab_name_array.count LOOP

	DBMS_OUTPUT.PUT_LINE ('--START : Create DDL For Table :'||tab_name_array(i) || ' ....');
  
WITH COLUMN_DEFINITION AS (
SELECT
    TABLE_NAME,
    COLUMN_NAME,
    CASE
        WHEN (DATA_TYPE= 'NUMBER' AND DATA_SCALE = 0 AND DATA_PRECISION <= 9) THEN 'INTEGER'
        WHEN (DATA_TYPE= 'NUMBER' AND DATA_SCALE = 0 AND DATA_PRECISION <= 18) THEN 'BIGINT'
        WHEN (DATA_TYPE= 'NUMBER' AND DATA_SCALE = 0 AND DATA_PRECISION >= 19) THEN 'DECIMAL(' || DATA_PRECISION || ',0)'
        WHEN (DATA_TYPE= 'NUMBER' AND DATA_SCALE > 0)  THEN 'DECIMAL(' || DATA_PRECISION || ',' || DATA_SCALE ||')'
        WHEN (DATA_TYPE= 'NUMBER' AND nvl(DATA_SCALE,0) = 0 AND nvl(DATA_PRECISION,0) = 0) THEN 'DECIMAL(38,18)'
        WHEN DATA_TYPE= 'CHAR' THEN 'VARCHAR(' || DATA_LENGTH || ')'
        WHEN DATA_TYPE= 'VARCHAR' THEN 'VARCHAR(' || DATA_LENGTH || ')'
        WHEN DATA_TYPE= 'VARCHAR2' THEN 'VARCHAR(' || DATA_LENGTH || ')'
        WHEN DATA_TYPE= 'DATE' THEN 'TIMESTAMP'
        WHEN DATA_TYPE= 'DATETIME' THEN 'TIMESTAMP'
        WHEN DATA_TYPE LIKE 'TIMESTAMP%' THEN 'TIMESTAMP'
        WHEN DATA_TYPE= 'LONG' THEN 'TEXT'
        WHEN DATA_TYPE= 'CLOB' THEN 'TEXT'
        WHEN DATA_TYPE LIKE '%RAW%' THEN 'TEXT'
        WHEN DATA_TYPE= 'NCHAR' THEN 'NCHAR(' || DATA_LENGTH || ')'
        WHEN DATA_TYPE= 'NVARCHAR' THEN 'NVARCHAR(' || DATA_LENGTH || ')'
        ELSE DATA_TYPE || '(' || DATA_LENGTH || ')'
        END AS REDSHIFT_COLUMN_DEFINITION
FROM ALL_TAB_COLUMNS
WHERE
    OWNER= SCHEMA_NAME
    AND TABLE_NAME = tab_name_array(i)
)

select listagg(text,'')  WITHIN group (order by rownum) into CREATE_DDL from (SELECT 'CREATE TABLE '|| SCHEMA_NAME||'.'||MAX(TABLE_NAME)||' (' AS TEXT FROM COLUMN_DEFINITION
UNION ALL
SELECT '   '||COLUMN_NAME||' '||REDSHIFT_COLUMN_DEFINITION || ', ' AS TEXT FROM COLUMN_DEFINITION
UNION ALL
SELECT ') ;' AS TEXT FROM DUAL);
 
  DBMS_OUTPUT.PUT_LINE (REPLACE(CREATE_DDL,', ) ;',' );'));
	DBMS_OUTPUT.PUT_LINE ('--END : Create DDL For Table :'||tab_name_array(i) || ' ....');
	END LOOP;
	DBMS_OUTPUT.PUT_LINE ('-- *END : LOOPING THORUGH Oracle TABLES & Generating Redshift DDLs **');
	EXCEPTION  WHEN OTHERS THEN
	DBMS_OUTPUT.put_line (DBMS_UTILITY.format_error_stack);
	RAISE; 
END;